openapi: 3.0.0
info:
  title: Arena Vendor Management API
  version: 2.0.0
  description: Backend API for managing arenas, vendors, assignments, and menus.
servers:
  - url: http://localhost:3000

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PickupSlot:
      type: object
      properties:
        name: { type: string, example: "Main Gate" }
        capacity: { type: integer, example: 50 }

    Arena:
      type: object
      properties:
        name: { type: string, example: "Food Expo" }
        date: { type: string, format: date }
        pickupSlots:
          type: array
          items:
            $ref: "#/components/schemas/PickupSlot"

    Vendor:
      type: object
      properties:
        name: { type: string }
        email: { type: string }
        status: { type: string, enum: ["active", "inactive"] }

    MenuItem:
      type: object
      properties:
        title: { type: string }
        price: { type: number }
        category: { type: string }
        isAvailable: { type: boolean }

    Assignment:
      type: object
      properties:
        arenaId: { type: string }
        vendorId: { type: string }
        pickupSlotId: { type: string }

security:
  - bearerAuth: []

paths:
  /api/arena:
    post:
      summary: Create an arena
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Arena" }
      responses:
        '201': { description: Created }

  /api/arena/{id}/vendors:
    get:
      summary: Get vendors assigned to an arena
      security: [ { bearerAuth: [] } ]
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
        - in: query
          name: page
          schema: { type: integer }
        - in: query
          name: limit
          schema: { type: integer }
      responses:
        '200': { description: Success }

  /api/vendor:
    post:
      summary: Create a vendor
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Vendor" }
      responses:
        '201': { description: Created }

  /api/vendor/{id}/menu:
    post:
      summary: Add a menu item
      security: [ { bearerAuth: [] } ]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/MenuItem" }
      responses:
        '200': { description: Updated }

  /api/assign:
    post:
      summary: Assign vendor to slot
      security: [ { bearerAuth: [] } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/Assignment" }
      responses:
        '201': { description: Created }
